### ISSUE TITLE
Zip file for release versions

### ISSUE THREAD

**Issue by EricAKAPode** [ajkroeg/LoanSharks#1]
Github is a bit awkward about downloading the jsons, it'd be more user friendly if we could download a single zip to our mods folder. Much appreciate the mod and am looking forward to events based on loan status and repossessions!

**Comment by ajkroeg** [comment]
Sure, I can throw a zip up there.

FWIW you won't get anything out of the mod just dumping it in your mods folder...you'll need to create your own loan item, add it to stores, and create your own events. This is more of a framework mod for devs/creators than a standalone, plug and play deal (if that makes sense).
